sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

# We want to cache the ~/.composer/cache directory between builds (this will speed things up)
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  # If you have jobs that are allowed to fail (for example, Bleeding Edge builds), 
  # adding this directive lets Travis CI decide “well, everything that’s required 
  # to pass has done so, so we can consider this build a success.” 
  # This will help speed up the feedback loop from the time code is pushed to the time 
  # you know everything’s good.
  fast_finish: true
  include:
    - name: Coding standards
      php: 7.3
      env: WP_VERSION=latest

    # Canary for our oldest-supported version
    - name: Legacy
      php: 5.6
      env: WP_VERSION=4.9

    # Nightly versions of PHP and WordPress.
    - name: Bleeding edge
      php: 7.4snapshot
      env: WP_VERSION=trunk

  # Jobs that are permitted to fail without breaking the build
  allow_failures:
    - name: Bleeding edge

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Unless we need XDebug, disable it for improved performance.
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

  # Install an older version of PHPUnit if we're still running PHP 5.6.
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

  # If we've set the $WP_TRAVISCI variable to run PHPCS, do that instead
  # of running PHPUnit.
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  # Optionally run the tests again in a multisite environment
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi

  # If we've set the $WP_TRAVISCI variable to run PHPCS, do that instead
  # of running PHPUnit.
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
